package com.deepseek.plugin.chat

import com.deepseek.plugin.i18n.I18n
import com.deepseek.plugin.store.ChangeManagementStore
import com.deepseek.plugin.store.ChangeRecord
import com.deepseek.plugin.store.FileChangeInfo
import com.intellij.openapi.command.WriteCommandAction
import com.intellij.openapi.project.Project
import com.intellij.openapi.vfs.LocalFileSystem
import java.io.File

/**
 * Parses and applies file operations generated by the AI coding agent.
 *
 * Extracted from ChatPanel to reduce file size and enable unit testing.
 */
class FileOperationExecutor(
    private val project: Project,
    private val addMessageLabel: (String) -> Unit,
    private val getSourceRootPaths: () -> List<String>
) {
    /** Cache of project source root paths, computed once per operation */
    private var cachedSourceRoots: List<File>? = null

    data class FileOperation(
        val path: String,
        val content: String,
        val action: String // "write" or "delete"
    )

    /**
     * Parse the AI response to extract file operations.
     * Format: <file path="..."> ...content... </file>
     */
    fun parseFileOperations(response: String): List<FileOperation> {
        val operations = mutableListOf<FileOperation>()

        // 正则1：带 ```代码围栏``` 的标准格式（兼容 CRLF、多余空白）
        val fileRegex = Regex(
            """<file\s+path="([^"]+)"(?:\s+action="([^"]*)")?\s*>(?:\r?\n)?\s*```(\w+)?\s*(?:\r?\n)?\s*([\s\S]*?)\s*```\s*(?:\r?\n)?\s*</file>""",
            RegexOption.MULTILINE
        )
        for (match in fileRegex.findAll(response)) {
            val path = match.groupValues[1].trim()
            val action = match.groupValues[2].ifBlank { "write" }
            val content = match.groupValues[4].trim()
            operations.add(FileOperation(path, content, action))
        }

        // 正则2：不带 ```围栏``` 的简洁格式（纯文本/配置文件）
        val simpleFileRegex = Regex(
            """<file\s+path="([^"]+)"(?:\s+action="([^"]*)")?\s*>([\s\S]*?)</file>""",
            RegexOption.MULTILINE
        )
        for (match in simpleFileRegex.findAll(response)) {
            val path = match.groupValues[1].trim()
            val action = match.groupValues[2].ifBlank { "write" }
            val content = match.groupValues[3].trim()
            if (operations.none { it.path == path }) {
                operations.add(FileOperation(path, content, action))
            }
        }

        // 调试日志
        if (operations.isEmpty() && response.contains("<file")) {
            System.err.println("[Agent] parseFileOperations: found <file> tags but no regex matched. Response snippet: ${response.take(500)}")
        } else if (operations.isNotEmpty()) {
            System.err.println("[Agent] parseFileOperations: ${operations.size} operations parsed")
        }

        return operations
    }

    /**
     * Apply file operations to the project using IntelliJ's virtual file system.
     * Performs path traversal validation and user confirmation.
     */
    fun applyFileOperations(operations: List<FileOperation>, planResponse: String? = null) {
        // Reset cached paths for fresh scan
        cachedSourceRoots = null

        val projectBasePath = project.basePath ?: return
        val projectDir = File(projectBasePath).canonicalPath

        // Filter out paths that escape the project directory
        val safeOps = operations.filter { op ->
            val targetFile = File(projectBasePath, op.path)
            val canonicalPath = try {
                targetFile.canonicalPath
            } catch (_: Exception) {
                null
            }
            if (canonicalPath == null || !canonicalPath.startsWith(projectDir)) {
                addMessageLabel(I18n.tr("chat.skip.unsafe.path") + " " + op.path)
                false
            } else {
                true
            }
        }

        if (safeOps.isEmpty()) {
            addMessageLabel(I18n.tr("chat.no.safe.operations"))
            return
        }

        // Build confirmation message
        val summaryLines = mutableListOf<String>()
        var writeCount = 0
        var deleteCount = 0
        for (op in safeOps) {
            when (op.action) {
                "delete" -> {
                    val f = File(projectBasePath, op.path)
                    if (f.exists()) {
                        summaryLines.add(I18n.tr("chat.delete.prefix") + " " + op.path)
                        deleteCount++
                    }
                }
                else -> {
                    val f = File(projectBasePath, op.path)
                    if (f.exists()) {
                        summaryLines.add(I18n.tr("chat.modify.prefix") + " " + op.path)
                    } else {
                        summaryLines.add(I18n.tr("chat.create.prefix") + " " + op.path)
                    }
                    writeCount++
                }
            }
        }
        val confirmMsg = I18n.tr("chat.confirm.file.operations.header") + "\n\n" + summaryLines.joinToString("\n") +
                "\n\n" + I18n.tr("chat.confirm.execute.question")

        val confirmed = com.intellij.openapi.ui.Messages.showYesNoDialog(
            project,
            confirmMsg,
            I18n.tr("chat.confirm.agent.action"),
            I18n.tr("chat.confirm.execute"),
            I18n.tr("chat.cancel"),
            com.intellij.openapi.ui.Messages.getQuestionIcon()
        )
        if (confirmed != com.intellij.openapi.ui.Messages.YES) {
            addMessageLabel(I18n.tr("chat.agent.cancelled"))
            return
        }

        // 收集结果和文件变更
        var resultMsg = ""
        var hasModifiedFiles = false

        WriteCommandAction.runWriteCommandAction(project) {
            var created = 0
            var modified = 0
            var deleted = 0
            val fileChanges = mutableListOf<FileChangeInfo>()

            for (op in safeOps) {
                val targetFile = File(projectBasePath, op.path)

                when (op.action) {
                    "delete" -> {
                        val vf = LocalFileSystem.getInstance().findFileByIoFile(targetFile)
                        if (vf != null && vf.exists()) {
                            try {
                                vf.delete(this)
                                deleted++
                            } catch (e: Exception) {
                                System.err.println("[Agent] delete failed: ${op.path} - ${e.message}")
                            }
                        }
                    }
                    else -> {
                        val resolvedFile = resolveToExistingSourceRoot(targetFile)
                        val effectiveFile = resolvedFile ?: targetFile
                        val effectiveParent = effectiveFile.parentFile

                        if (resolvedFile == null && effectiveParent != null) {
                            val existingAncestor = findExistingAncestor(effectiveParent)
                            if (existingAncestor == null) {
                                System.err.println("[Agent] path ${op.path} does not match any existing source root")
                            }
                        }

                        try {
                            effectiveParent?.mkdirs()
                        } catch (e: Exception) {
                            System.err.println("[Agent] mkdirs failed for ${effectiveParent}: ${e.message}")
                        }

                        val contentBytes = op.content.toByteArray(Charsets.UTF_8)
                        val isNew = !effectiveFile.exists()

                        if (isNew) {
                            val parentVFile = LocalFileSystem.getInstance()
                                .findFileByIoFile(effectiveFile.parentFile)
                            if (parentVFile != null && parentVFile.exists()) {
                                try {
                                    val vf = parentVFile.createChildData(this, effectiveFile.name)
                                    vf.setBinaryContent(contentBytes)
                                    created++
                                    fileChanges.add(FileChangeInfo(effectiveFile.absolutePath, ByteArray(0), isNew = true))
                                } catch (e: Exception) {
                                    System.err.println("[Agent] VFS create failed for ${op.path}: ${e.message}")
                                    effectiveFile.writeBytes(contentBytes)
                                    LocalFileSystem.getInstance().refreshIoFiles(listOf(effectiveFile))
                                    created++
                                    fileChanges.add(FileChangeInfo(effectiveFile.absolutePath, ByteArray(0), isNew = true))
                                }
                            } else {
                                effectiveFile.writeBytes(contentBytes)
                                LocalFileSystem.getInstance().refreshIoFiles(listOf(effectiveFile))
                                created++
                                fileChanges.add(FileChangeInfo(effectiveFile.absolutePath, ByteArray(0), isNew = true))
                            }
                        } else {
                            // 备份原始内容
                            try {
                                val originalBytes = effectiveFile.readBytes()
                                fileChanges.add(FileChangeInfo(effectiveFile.absolutePath, originalBytes))
                            } catch (e: Exception) {
                                System.err.println("[Agent] backup (in-memory) failed for ${op.path}: ${e.message}")
                            }

                            try {
                                val vf = LocalFileSystem.getInstance().findFileByIoFile(effectiveFile)
                                if (vf != null && vf.exists()) {
                                    vf.setBinaryContent(contentBytes)
                                    modified++
                                } else {
                                    effectiveFile.writeBytes(contentBytes)
                                    LocalFileSystem.getInstance().refreshIoFiles(listOf(effectiveFile))
                                    modified++
                                }
                            } catch (e: Exception) {
                                System.err.println("[Agent] write failed for ${op.path}: ${e.message}")
                                try {
                                    effectiveFile.writeBytes(contentBytes)
                                    LocalFileSystem.getInstance().refreshIoFiles(listOf(effectiveFile))
                                    modified++
                                } catch (e2: Exception) {
                                    System.err.println("[Agent] fallback write also failed for ${op.path}: ${e2.message}")
                                }
                            }
                        }
                    }
                }
            }

            // Refresh project view
            val projectVDir = LocalFileSystem.getInstance().findFileByIoFile(File(projectBasePath))
            if (projectVDir != null) {
                projectVDir.refresh(false, true)
            }

            resultMsg = buildString {
                appendLine(I18n.tr("chat.agent.complete"))
                if (created > 0) appendLine(I18n.tr("chat.created.files") + " " + created + I18n.tr("chat.count.suffix"))
                if (modified > 0) appendLine(I18n.tr("chat.modified.files") + " " + modified + I18n.tr("chat.count.suffix"))
                if (deleted > 0) appendLine(I18n.tr("chat.deleted.files") + " " + deleted + I18n.tr("chat.count.suffix"))
                if (created == 0 && modified == 0 && deleted == 0) {
                    appendLine("- (没有文件操作被应用)")
                }
            }
            if (fileChanges.isNotEmpty()) {
                val semanticTitle = planResponse?.let { plan ->
                    val skipPatterns = listOf(
                        "输出格式", "项目结构", "相关源文件", "源码根目录",
                        "分析", "计划", "注意事项", "依赖关系", "规则"
                    )
                    plan.lines().firstOrNull { line ->
                        val trimmed = line.trim()
                        val heading = trimmed.replace(Regex("^#+\\s*"), "").trim()
                        trimmed.startsWith("#") && heading.isNotBlank() &&
                                skipPatterns.none { heading.contains(it) }
                    }?.replace(Regex("^#+\\s*"), "")?.trim()
                }
                val summary = if (!semanticTitle.isNullOrBlank()) {
                    semanticTitle
                } else {
                    val allPaths = safeOps.map { it.path.substringAfterLast("/").substringAfterLast("\\") }
                    val totalChanged = created + modified + deleted
                    if (totalChanged <= 2) {
                        allPaths.joinToString("、")
                    } else {
                        buildString {
                            if (created > 0) append("新建 ${created} 个文件")
                            if (modified > 0) { if (isNotEmpty()) append("，"); append("修改 ${modified} 个文件") }
                            if (deleted > 0) { if (isNotEmpty()) append("，"); append("删除 ${deleted} 个文件") }
                        }
                    }
                }
                val record = ChangeRecord(
                    title = I18n.tr("chat.change.title.prefix") + " ${summary.ifEmpty { I18n.tr("chat.unknown") }}",
                    changes = fileChanges
                )
                project.getService(ChangeManagementStore::class.java).addRecord(record)
                hasModifiedFiles = true
            }
        }

        addMessageLabel(resultMsg)
        if (hasModifiedFiles) {
            addMessageLabel(I18n.tr("chat.change.recorded"))
        }
    }

    // ===== Smart path resolution helpers =====

    /**
     * Try to resolve a target file path to an existing source root.
     * If the AI says "src/main/java/com/example/X.java" but the project uses
     * "src/main/kotlin/com/example/", this remaps to the existing kotlin dir.
     */
    private fun resolveToExistingSourceRoot(targetFile: File): File? {
        val basePath = project.basePath ?: return null
        val baseDir = File(basePath)

        if (targetFile.exists()) return null

        val relativePath = try {
            targetFile.canonicalPath.removePrefix(baseDir.canonicalPath).trimStart('/').replace('\\', '/')
        } catch (_: Exception) { return null }

        if (relativePath.isEmpty()) return null

        val sourceRoots = getSourceRootPaths()

        for (root in sourceRoots) {
            if (relativePath.startsWith(root.trimStart('/'))) {
                return null
            }
        }

        val sourceRootPatterns = listOf(
            "src/main/java/", "src/main/kotlin/", "src/main/resources/",
            "src/test/java/", "src/test/kotlin/", "src/test/resources/",
            "java/", "kotlin/", "resources/"
        )
        val packagePart = sourceRootPatterns
            .firstOrNull { relativePath.contains(it) }
            ?.let { relativePath.substringAfter(it) }
            ?: relativePath

        for (root in sourceRoots) {
            val candidate = File(root, packagePart)
            if (candidate.parentFile?.exists() == true) {
                return candidate
            }
            val existingFile = findFileByNameInProject(candidate.name)
            if (existingFile != null && existingFile.parentFile?.exists() == true) {
                return File(existingFile.parentFile, candidate.name)
            }
        }

        // Last resort: try each source root
        for (root in sourceRoots) {
            val candidate = File(root, packagePart)
            if (candidate.parentFile?.exists() == true) return candidate
        }
        return null
    }

    private fun findExistingAncestor(file: File): File? {
        var current = file
        while (current != null) {
            if (current.exists()) return current
            current = current.parentFile
        }
        return null
    }

    private fun findFileByNameInProject(fileName: String): File? {
        val basePath = project.basePath ?: return null
        val baseDir = File(basePath)
        return baseDir.walkTopDown()
            .find { it.isFile && it.name == fileName }
    }
}
